#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export PATH="${PATH}:$HOME/.local/bin"

wmname LG3D
wmname compiz
export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	# FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	# BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	# RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	# GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	# YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	# CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	# WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# Display
# bash "$HOME"/.screenlayout/display-tecpan.sh
bash "$HOME"/.screenlayout/display.sh

# Configurations -------------------------------#
if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
    bspc monitor eDP1 -d 'I' 'II' 'III' 'IV' 'V'
    bspc monitor HDMI1 -d 'VI' 'VII' 'VIII'
    # bspc monitor HDMI1 -d 'I' 'II' 'III' 'IV' 'V'
    # bspc monitor eDP1 -d 'VI' 'VII' 'VIII'
else
    bspc monitor eDP1 -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
fi

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$MAGENTA"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on

# 3 > file
bspc rule -a Pavucontrol desktop='^3' focus=on

# # 5 > media
# declare -a media=(Audacity mplayer lxmusic Gimp Gimp-2.8)
# for i in ${media[@]}; do
#    bspc rule -a $i desktop='^5' follow=on focus=on; done

# # 6 > settings
# bspc rule -a GParted desktop='^6' follow=on focus=on
# declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
# System-config-printer.py Exo-helper-1)
# for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# # 9 > Exclusive Pavucontrol
# declare -a settings=(Pavucontrol)
# for i in ${settings[@]}; do
#    bspc rule -a $i desktop='^6' state=tiled follow=on focus=on; done

# special rules
bspc rule -a qalc state=floating rectangle=500x400+0+0 center=true follow=on focus=on
bspc rule -a Anamnesis state=floating rectangle=500x400+0+0 center=true follow=on focus=on 
bspc rule -a countd state=floating rectangle=900x300+0+0 center=true follow=on focus=on

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager polybar anamnesis

# Lauch xsettingsd daemon
xsettingsd &

# Lauch dunst daemon
dunst &

# polkit agent
#/usr/lib/xfce-polkit/xfce-polkit &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
# ksuperkey -e 'Super_L=Alt_L|F1' &
# ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash "$HOME"/.fehbg

# Unblock Bluetooth
# rfkill unblock all

# Start pavucontrol
[[ $(pidof pavucontrol) ]] || pavucontrol &

# Start kdeconnect 
[[ $(pidof kdeconnectd) ]] || kdeconnect-cli &

# Execute Xmodmap
xmodmap /home/sayago/.Xmodmap

# Start mpd
mpd &

# Change sped typing
xset r rate 300 50

# Start anamnesis
anamnesis --start

# Start bspwm scripts
bspcolors
bspcomp
bspbar
# focusing &
# bspfloat &

## Adjust backlight (AMD)
#blight -d amdgpu_bl0 set 15%

# Stop Music
# [[ $(mpc status) == *"[playing]"* ]] && mpc stop

# reload kitty
pgrep -l kitty | grep -Eo "[0-9]{3,}" | xargs kill -SIGUSR1
